### PR TITLE
Change Kinnari font to Angsana

### PR DESCRIPTION
**Pull request by zartre**

### CODE REVIEW

**Comment by zartre** [comment]
The build failed because Angsana font files don't exist in the repo and I don't think I will add them 🤔🤔 Copyright issue.

**Comment by sagelga** [comment]
Note to GitHub. This PR shall :
- Resolves #22

**Comment by kavinvin** [comment]
Can we just ignore the copyright? I'm pretty sure building a LaTeX file using Angsana New without having the font files is impossible.

**Comment by zartre** [comment]
Hmmm I dont' feel like taking a risk. May you just merge it lel

**Comment by kavinvin** [comment]
This should work now.

**Pull request merged**
